### use balance1
POST http://localhost:8080/transaction/use
Content-Type: application/json

{
  "userId": 1,
  "accountNumber": "1000000002",
  "amount": 100
}

### use balance2
POST http://localhost:8080/transaction/use
Content-Type: application/json

{
  "userId": 1,
  "accountNumber": "1000000002",
  "amount": 100
}

### cancel use balance
POST http://localhost:8080/transaction/cancel
Content-Type: application/json

{
  "transactionId": "a14bc9b727314204ac2cce8a4b3e0e18",
  "accountNumber": "1000000002",
  "amount": 100
}

### query transaction
GET http://localhost:8080/transaction/b571becfc3c348f4a84bfdb25a2cc510
